server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka
spring:
  application:
    name: zuul
zuul:
  ignoredServices: '*'
  routes:
    api-a:
      path: /user/**
      service-id: user
    api-b:
      path: /car/**
      service-id: car